spring:
  # MYSQL DATABASE CONFIG
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    initialization-mode: always
    continue-on-error: true
    url: jdbc:mysql://localhost:3306/tale?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
